### ISSUE TITLE
conflict

### ISSUE THREAD

**Issue by tono-maron** [tono-maron/nokin_app#13]
ひろきたのむじゃけぇ

**Comment by ia17011** [comment]
Gemfile.lockのコンフリクト?
bundle installせずにpushしたみたいな感じかな。分からん

**Comment by ia17011** [comment]
一回そのブランチでgit stashして、リモートブランチをpullしてみたら良いと思う.
それでそのstashを復元して、コンフリクト多分起きるから、起きた部分をローカルで直してみて。

**Comment by ia17011** [comment]
それかもうそのプルリクをマージ強行して、GitHub上でコンフリクト直す方が早いかな。
>> HEAD ~~~ みたいな感じで、ブランチごとのコードが出てくるから、そのブランチじゃなくて、既存のブランチ(最新)のコードを残せばok。

**Comment by tono-maron** [comment]
マージ強行するわ
